const keyvalue: any ={
    city:[
        'a.thirumuruganpoondi (tamil nadu)',
        'a.vellalapatti (tamil nadu)',
        'aadityana (gujarat)',
        'aambaliyasan (gujarat)',
        'aantaliya (gujarat)',
        'aarambhada (gujarat)',
        'abhayapuri (assam)',
        'abiramam (tamil nadu)',
        'abohar (punjab)',
        'abrama (gujarat)',
        'abu road (rajasthan)',
        'achabal (jammu & kashmir)',
        'achalpur (maharashtra)',
        'achampudur (tamil nadu)',
        'acharapakkam (tamil nadu)',
        'achhalda (uttar pradesh)',
        'achhnera (uttar pradesh)',
        'achipatti (tamil nadu)',
        'adikaratti (tamil nadu)',
        'adilabad (andhra pradesh)',
        'adityapur (jharkhand)',
        'adoni (andhra pradesh)',
        'adra (west bengal)',
        'aduthurai alias maruthuvakudi (tamil nadu)',
        'adyar (karnataka)',
        'afzalgarh (uttar pradesh)',
        'agarwal mandi (uttar pradesh)',
        'ahmadnagar (maharashtra)',
        'ahmadpur (maharashtra)',
        'ahmadpur (west bengal)',
        'ahmedabad (gujarat)',
        'ahmedabad cantonment (gujarat)',
        'aiho (west bengal)',
        'air force area (uttar pradesh)',
        'aistala (west bengal)',
        'aizawl (mizoram)',
        'ajra (maharashtra)',
        'akhnoor (jammu & kashmir)',
        'akkalkot (maharashtra)',
        'akkarampalle (andhra pradesh)',
        'akola (maharashtra)',
        'akot (maharashtra)',
        'alandi (maharashtra)',
        'alanganallur (tamil nadu)',
        'alangulam (tamil nadu)',
        'alibag (maharashtra)',
        'aligarh (uttar pradesh)',
        'alipurduar (west bengal)',
        'alipurduar rly.jnc. (west bengal)',
        'allahabad (uttar pradesh)',
        'allahganj (uttar pradesh)',
        'aluva (kerala)',
        'amanpur (uttar pradesh)',
        'amarpur (bihar)',
        'ambad (maharashtra)',
        'ambarnath (maharashtra)',
        'ambasamudram (tamil nadu)',
        'ambattur (tamil nadu)',
        'ambejogai (maharashtra)',
        'amguri (assam)',
        'aminagar urf bhurbaral (uttar pradesh)',
        'amlabad (jharkhand)',
        'amli (dadra & nagar haveli *)',
        'ammoor (tamil nadu)',
        'amodghata (west bengal)',
        'amraudha (uttar pradesh)',
        'amravati (maharashtra)',
        'amritsar (punjab)',
        'amritsar cantt. (punjab)',
        'anandapur (odisha)',
        'angarpathar (jharkhand)',
        'anjangaon (maharashtra)',
        'anklesvar (gujarat)',
        'anpara (uttar pradesh)',
        'anugul (odisha)',
        'anupshahr (uttar pradesh)',
        'aquem (goa)',
        'ara (jharkhand)',
        'araria (bihar)',
        'areraj (bihar)',
        'arookutty (kerala)',
        'arra (west bengal)',
        'arrah (bihar)',
        'arvi (maharashtra)',
        'asansol (west bengal)',
        'asarganj (bihar)',
        'ashoknagar kalyangarh (west bengal)',
        'ashta (maharashtra)',
        'asika (odisha)',
        'asola (delhi *)',
        'ateli (haryana)',
        'athagad (odisha)',
        'athmallik (odisha)',
        'atrauli (uttar pradesh)',
        'atraulia (uttar pradesh)',
        'aurangabad (bihar)',
        'aurangabad (maharashtra)',
        'aurangabad (west bengal)',
        'ausa (maharashtra)',
        'avanashi (tamil nadu)',
        'awantipora (jammu & kashmir)',
        'babar pur (delhi *)',
        'baberu (uttar pradesh)',
        'babua kalan (jharkhand)',
        'badami bagh (jammu & kashmir)',
        'baddi (himachal pradesh)',
        'badgam (jammu & kashmir)',
        'badlapur (maharashtra)',
        'badrinathpuri (uttaranchal)',
        'bagbera (jharkhand)',
        'bahadurganj (bihar)',
        'bakloh (himachal pradesh)',
        'balangir (odisha)',
        'balapur (maharashtra)',
        'balasinor (gujarat)',
        'baleshwar (odisha)',
        'baliari (jharkhand)',
        'balimela (odisha)',
        'balkundra (jharkhand)',
        'ballia (uttar pradesh)',
        'bally (west bengal)',
        'balugaon (odisha)',
        'bambolim (goa)',
        'banapur (odisha)',
        'bandipore (jammu & kashmir)',
        'bangalore (karnataka)',
        'bangaon (west bengal)',
        'bangura (odisha)',
        'banjar (himachal pradesh)',
        'banki (odisha)',
        'bankner (delhi *)',
        'bankura (west bengal)',
        'banmankhi bazar (bihar)',
        'barajamda (jharkhand)',
        'baramati (maharashtra)',
        'baramula (jammu & kashmir)',
        'barbil (odisha)',
        'bargarh (odisha)',
        'baripada (odisha)',
        'barshi (maharashtra)',
        'barua sagar (uttar pradesh)',
        'barwadih (jharkhand)',
        'barwani (madhya pradesh)',
        'basmath (maharashtra)',
        'basudebpur (odisha)',
        'baudhgarh (odisha)',
        'bawana (delhi *)',
        'begum pur (delhi *)',
        'begusarai (bihar)',
        'belgaum (karnataka)',
        'belpahar (odisha)',
        'berasia (madhya pradesh)',
        'betul (madhya pradesh)',
        'bhadrak (odisha)',
        'bhagatdih (jharkhand)',
        'bhandara (maharashtra)',
        'bhanjanagar (odisha)',
        'bharuch (gujarat)',
        'bharuch ina (gujarat)',
        'bhati (delhi *)',
        'bhawani mandi (rajasthan)',
        'bhawanipatna (odisha)',
        'bhind (madhya pradesh)',
        'bhiwandi (maharashtra)',
        'bhokardan (maharashtra)',
        'bhopal (madhya pradesh)',
        'bhor (maharashtra)',
        'bhowrah (jharkhand)',
        'bhuban (odisha)',
        'bhubaneswar (odisha)',
        'bhum (maharashtra)',
        'bhusawal (maharashtra)',
        'bicholim (goa)',
        'bid (maharashtra)',
        'bidar (karnataka)',
        'bihar (bihar)',
        'bilaspur (himachal pradesh)',
        'biloli (maharashtra)',
        'binika (odisha)',
        'biramitrapur (odisha)',
        'bishnupur (manipur)',
        'bishnupur (west bengal)',
        'biswanath chariali (assam)',
        'boisar (maharashtra)',
        'bokaro (jharkhand)',
        'bokaro steel city (jharkhand)',
        'bomdila (arunachal pradesh)',
        'bommasandra (karnataka)',
        'bowali (west bengal)',
        'brahmapur (odisha)',
        'brajarajnagar (odisha)',
        'buldana (maharashtra)',
        'bundi (rajasthan)',
        'calangute (goa)',
        'calapor (goa)',
        'chakan (maharashtra)',
        'chalisgaon (maharashtra)',
        'champawat (uttaranchal)',
        'chandigarh (chandigarh *)',
        'chandrapur (maharashtra)',
        'chandurbazar (maharashtra)',
        'chengalpattu (tamil nadu)',
        'chennai (tamil nadu)',
        'chennasamudram (tamil nadu)',
        'chhatrapur (odisha)',
        'chhora (west bengal)',
        'chicalim (goa)',
        'chikhli (maharashtra)',
        'chikiti (odisha)',
        'chikodi (karnataka)',
        'chinnasalem (tamil nadu)',
        'chiplun (maharashtra)',
        'chirgaon (uttar pradesh)',
        'chopda (maharashtra)',
        'choudwar (odisha)',
        'coimbatore (tamil nadu)',
        'curti (goa)',
        'cuttack (odisha)',
        'dalhousie (himachal pradesh)',
        'dallo pura (delhi *)',
        'daltonganj (jharkhand)',
        'damanjodi (odisha)',
        'dapoli camp (maharashtra)',
        'daryapur banosa (maharashtra)',
        'daund (maharashtra)',
        'deglur (maharashtra)',
        'dehradun (uttaranchal)',
        'dehu road (maharashtra)',
        'delhi cantt. (delhi *)',
        'delhi municipal corporation (u) (delhi *)',
        'deoghar (jharkhand)',
        'deoli (delhi *)',
        'deoli (maharashtra)',
        'deoria (uttar pradesh)',
        'deulgaon raja (maharashtra)',
        'dewas (madhya pradesh)',
        'dhanbad (jharkhand)',
        'dhar (madhya pradesh)',
        'dharmabad (maharashtra)',
        'dharoti khurd (uttar pradesh)',
        'dhenkanal (odisha)',
        'dhule (maharashtra)',
        'digapahandi (odisha)',
        'dondaicha-warwade (maharashtra)',
        'dulhipur (uttar pradesh)',
        'dwarka (gujarat)',
        'ekambara kuppam (andhra pradesh)',
        'english bazar (west bengal)',
        'fertilzer corporation of indiatownship (odisha)',
        'gabberia (west bengal)',
        'gadchiroli (maharashtra)',
        'gagret (himachal pradesh)',
        'gandhidham (gujarat)',
        'gandhinagar (maharashtra)',
        'ganjam (odisha)',
        'garacharma (andaman & nicobar islands *)',
        'garalgachha (west bengal)',
        'gawan (uttar pradesh)',
        'ghaziabad (uttar pradesh)',
        'giridih (jharkhand)',
        'gondiya (maharashtra)',
        'gopalpur (odisha)',
        'gorakhpur (uttar pradesh)',
        'goregaon (maharashtra)',
        'greater mumbai (maharashtra)',
        'guhagar (maharashtra)',
        'gulbarga (karnataka)',
        'gulmarg (jammu & kashmir)',
        'gunupur (odisha)',
        'gurgaon (haryana)',
        'gurgaon rural (haryana)',
        'guruvayoor (kerala)',
        'hadgaon (maharashtra)',
        'haludbani (jharkhand)',
        'hamirpur (himachal pradesh)',
        'hathras (uttar pradesh)',
        'hinganghat (maharashtra)',
        'hingoli (maharashtra)',
        'hinjilicut (odisha)',
        'hirakud (odisha)',
        'hisar (haryana)',
        'hyderabad (uttar pradesh)',
        'hyderabad m.corp (andhra pradesh)',
        'ichalkaranji (maharashtra)',
        'igatpuri (maharashtra)',
        'indapur (maharashtra)',
        'indore (madhya pradesh)',
        'jabalpur (madhya pradesh)',
        'jagatsinghapur (odisha)',
        'jaipur (rajasthan)',
        'jajapur (odisha)',
        'jaleswar (odisha)',
        'jalgaon (jamod) (maharashtra)',
        'jalgaon (maharashtra)',
        'jalna (maharashtra)',
        'jammu (jammu & kashmir)',
        'jamshedpur (jharkhand)',
        'jatani (odisha)',
        'jawalamukhi (himachal pradesh)',
        'jaysingpur (maharashtra)',
        'jejuri (maharashtra)',
        'jeypur (odisha)',
        'jhansi (uttar pradesh)',
        'jharia (jharkhand)',
        'jharsuguda (odisha)',
        'jhinkpani (jharkhand)',
        'jhusi (uttar pradesh)',
        'jhusi kohna (uttar pradesh)',
        'jintur (maharashtra)',
        'joda (odisha)',
        'joya (uttar pradesh)',
        'junnar (maharashtra)',
        'kabnur (maharashtra)',
        'kadaura (uttar pradesh)',
        'kagal (maharashtra)',
        'kaimganj (uttar pradesh)',
        'kalambe turf thane (maharashtra)',
        'kalamnuri (maharashtra)',
        'kalikapur (jharkhand)',
        'kalinagar (uttar pradesh)',
        'kalka (haryana)',
        'kalyan-dombivali (maharashtra)',
        'kamareddy (andhra pradesh)',
        'kamptee (maharashtra)',
        'kankavli (maharashtra)',
        'kannad (maharashtra)',
        'kannauj (uttar pradesh)',
        'kanniyakumari (tamil nadu)',
        'kanth (uttar pradesh)',
        'kantilo (odisha)',
        'kanyanagar (west bengal)',
        'kapas hera (delhi *)',
        'karad (maharashtra)',
        'karanja (maharashtra)',
        'karanje turf satara (maharashtra)',
        'karawal nagar (delhi *)',
        'kargil (jammu & kashmir)',
        'karjat (maharashtra)',
        'karnawal (uttar pradesh)',
        'karwar (karnataka)',
        'kasara budruk (maharashtra)',
        'katghar lalganj (uttar pradesh)',
        'kathera (uttar pradesh)',
        'katra (jammu & kashmir)',
        'kauriaganj (uttar pradesh)',
        'kavisuryanagar (odisha)',
        'kendra khottamdi (west bengal)',
        'kendrapara (odisha)',
        'kendujhar (odisha)',
        'khalikote (odisha)',
        'khalilabad (uttar pradesh)',
        'khamaria (uttar pradesh)',
        'khamgaon (maharashtra)',
        'khargupur (uttar pradesh)',
        'khariar (odisha)',
        'khariya (uttar pradesh)',
        'khed (maharashtra)',
        'khekada (uttar pradesh)',
        'khopoli (maharashtra)',
        'khordha (odisha)',
        'khuldabad (maharashtra)',
        'kirkee (maharashtra)',
        'kishunpur (uttar pradesh)',
        'kithaur (uttar pradesh)',
        'kochi (kerala)',
        'kolhapur (maharashtra)',
        'kolkata (west bengal)',
        'kopargaon (maharashtra)',
        'koraput (odisha)',
        'koratagere (karnataka)',
        'kosi kalan (uttar pradesh)',
        'kotpad (odisha)',
        'kozhikode (kerala)',
        'kuchaman city (rajasthan)',
        'lalitpur (uttar pradesh)',
        'latehar (jharkhand)',
        'latur (maharashtra)',
        'leh (jammu & kashmir)',
        'loha (maharashtra)',
        'lonavala (maharashtra)',
        'lucknow (uttar pradesh)',
        'ludhiana (punjab)',
        'madhavnagar (maharashtra)',
        'mahabaleshwar (maharashtra)',
        'mahad (maharashtra)',
        'maheshwar (madhya pradesh)',
        'mahrajganj (uttar pradesh)',
        'malegaon (maharashtra)',
        'malkangiri (odisha)',
        'mallawan (uttar pradesh)',
        'manali (himachal pradesh)',
        'manchar (maharashtra)',
        'mangalvedhe (maharashtra)',
        'manmad (maharashtra)',
        'manwath (maharashtra)',
        'mapusa (goa)',
        'margao (goa)',
        'matheran (maharashtra)',
        'mhasla (maharashtra)',
        'mira-bhayandar (maharashtra)',
        'mormugao (goa)',
        'morshi (maharashtra)',
        'mukhed (maharashtra)',
        'mukhiguda (odisha)',
        'murshidabad (west bengal)',
        'mysore (karnataka)',
        'nabarangapur (odisha)',
        'nagapur (maharashtra)',
        'nagpur (maharashtra)',
        'nala sopara (maharashtra)',
        'nalco (odisha)',
        'nanded-waghala (maharashtra)',
        'nandej (gujarat)',
        'nandgaon (maharashtra)',
        'nandura (maharashtra)',
        'nandurbar (maharashtra)',
        'nashik (maharashtra)',
        'navi mumbai (maharashtra)',
        'navi mumbai (panvel, raigarh) (maharashtra)',
        'nayagarh (odisha)',
        'neral (maharashtra)',
        'new delhi municipal council (delhi *)',
        'nilagiri (odisha)',
        'nimapada (odisha)',
        'nipani (karnataka)',
        'nizamabad (andhra pradesh)',
        'noida (uttar pradesh)',
        'nowshehra (jammu & kashmir)',
        'nuapatna (odisha)',
        'osmanabad (maharashtra)',
        // 'others',
        'pachora (maharashtra)',
        'padmapur (odisha)',
        'padrauna (uttar pradesh)',
        'pahalgam (jammu & kashmir)',
        'paithan (maharashtra)',
        'palghar (maharashtra)',
        'panaji (goa)',
        'panchgani (maharashtra)',
        'pandharpur (maharashtra)',
        'panhala (maharashtra)',
        'panvel (maharashtra)',
        'paonta sahib (himachal pradesh)',
        'paradip (odisha)',
        'paranda (maharashtra)',
        'parbhani (maharashtra)',
        'parlakhemundi (odisha)',
        'parli (maharashtra)',
        'partur (maharashtra)',
        'patna (bihar)',
        'patnagarh (odisha)',
        'patratu (jharkhand)',
        'pattamundai (odisha)',
        'patur (maharashtra)',
        'phaltan (maharashtra)',
        'phulabani (odisha)',
        'pimpri chinchwad (maharashtra)',
        'pithampur (madhya pradesh)',
        'polasara (odisha)',
        'ponda (goa)',
        'pul pehlad (delhi *)',
        'pulgaon (maharashtra)',
        'pulwama (jammu & kashmir)',
        'punch (jammu & kashmir)',
        'pune (maharashtra)',
        'puri (odisha)',
        'purna (maharashtra)',
        'purusottampur (odisha)',
        'qazigund (jammu & kashmir)',
        'rabupura (uttar pradesh)',
        'rahuri (maharashtra)',
        'raipur rani (haryana)',
        'rairangpur (odisha)',
        'rajapur (maharashtra)',
        'rajsamand (rajasthan)',
        'ramban (jammu & kashmir)',
        'rambha (odisha)',
        'rampur (uttar pradesh)',
        'ranchi (jharkhand)',
        'ratnagiri (maharashtra)',
        'raurkela (odisha)',
        'raurkela industrialship (odisha)',
        'raver (maharashtra)',
        'rayagada (odisha)',
        'remuna (odisha)',
        'rishikesh (uttaranchal)',
        'rudrapur (uttaranchal)',
        'sahjanwa (uttar pradesh)',
        'sambalpur (odisha)',
        'sancoale (goa)',
        'sandi (uttar pradesh)',
        'sangamner (maharashtra)',
        'sangareddy (andhra pradesh)',
        'sangli-miraj & kupwad (maharashtra)',
        'sangole (maharashtra)',
        'satana (maharashtra)',
        'satara (maharashtra)',
        'savda (maharashtra)',
        'sawantwadi (maharashtra)',
        'secunderabad (andhra pradesh)',
        'sgm (rajasthan)',
        'shahade (maharashtra)',
        'shahapur (maharashtra)',
        'shegaon (maharashtra)',
        'shillong cantt. (meghalaya)',
        'shimla (himachal pradesh)',
        'shirdi (maharashtra)',
        'shirur (maharashtra)',
        'shirwal (maharashtra)',
        'shivajinagar (maharashtra)',
        'shrirampur (maharashtra)',
        'shrirampur(rural) (maharashtra)',
        'siddipet (andhra pradesh)',
        'sikar (rajasthan)',
        'sillod (maharashtra)',
        'singampuneri (tamil nadu)',
        'singrauli (madhya pradesh)',
        'sinnar (maharashtra)',
        'solapur (maharashtra)',
        'sonapur (odisha)',
        'sonipat (haryana)',
        'soro (odisha)',
        'srinagar (jammu & kashmir)',
        'sriperumbudur (tamil nadu)',
        'str (rajasthan)',
        'sultan pur (delhi *)',
        'sunabeda (odisha)',
        'sundargarh (odisha)',
        'surat (gujarat)',
        'talcher (odisha)',
        'talegaon dabhade (maharashtra)',
        'tarapur (maharashtra)',
        'tasgaon (maharashtra)',
        'thane (maharashtra)',
        'thiruvallur (tamil nadu)',
        'thongkhong laxmi bazar (manipur)',
        'thoothukkudi (tamil nadu)',
        'tiruchirappalli (tamil nadu)',
        'tirupati (andhra pradesh)',
        'tiruppur (tamil nadu)',
        'titlagarh (odisha)',
        'tral (jammu & kashmir)',
        'tuljapur (maharashtra)',
        'udala (odisha)',
        'udgir (maharashtra)',
        'udhampur (jammu & kashmir)',
        'ulhasnagar (maharashtra)',
        'umarkote (odisha)',
        'una (himachal pradesh)',
        'uppal kalan (andhra pradesh)',
        'uran islampur (maharashtra)',
        'uttar raypur (west bengal)',
        'uttarkashi (uttaranchal)',
        'vadgaon (maharashtra)',
        'vadodara (gujarat)',
        'vaijapur (maharashtra)',
        'vapi (gujarat)',
        'varanasi (uttar pradesh)',
        'vasai (maharashtra)',
        'vasantnagar (maharashtra)',
        'vashind (maharashtra)',
        'vijayawada (andhra pradesh)',
        'viluppuram (tamil nadu)',
        'virar (maharashtra)',
        'visakhapatnam (andhra pradesh)',
        'vita (maharashtra)',
        'vizianagaram (andhra pradesh)',
        'wai (maharashtra)',
        'warangal (andhra pradesh)',
        'wardha (maharashtra)',
        'washim (maharashtra)',
        'yavatmal (maharashtra)',
        'yerkheda (maharashtra)',
        'yol (himachal pradesh)',
        'ziro (arunachal pradesh)',
        'zunheboto (nagaland)'
    ]
};



const getCityArray = (): string[] => {
   /* const returnValue: string[] = [];
    if (keyvalue.city) {
        for (const a of keyvalue.city) {
            returnValue.push(a.City);
        }
    }*/
    return keyvalue.city;
};

/*const getCityArray1 = (): string[] => {
    const returnValue: string[] = [];
    if (keyvalue.city) {
        for (const a of keyvalue.city) {
            const s: string = a.City + ' (' + a.State + ')';
            if (returnValue.indexOf(s) !== -1) {
                console.log('Value exists!');
            } else {
                returnValue.push(s.toLowerCase());
            }

        }
    }
    return returnValue;
};*/


export default {
    getCityArray
   /* getCityArray1*/
};
